### ISSUE TITLE
KeyError: 'allPlayers'

### ISSUE THREAD

**Issue by Eltex-Shvecov** [Eltex-Shvecov/LOLTracking#1]
Если во время загрузки матча когда уже API сервер создан, но игра еще не началась, нажать Connect, вылетает такая ошибка. Но когда игра уже начата, такой трассировки нет.

```
Server start
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Dmitry\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Dmitry\PycharmProjects\LOL\LOLGui.py", line 52, in click_connect
    self.LOL_Manager.start_application(self)
  File "C:\Users\Dmitry\PycharmProjects\LOL\LOLManager.py", line 45, in start_application
    all_players = self.Data['allPlayers']
KeyError: 'allPlayers'
```

**Comment by Eltex-Shvecov** [comment]
Причина была в получение поля которого нет. Не знал что есть get. Решилось всё проверкой поля в json при проверки запуска сервера по кнопке Connect. В последующем эту функцию проверки запуска можно убрать думаю и проверять сервер функцией update_data.

```
            if self.Data.get('allPlayers') is None:
                return False
            else:
                return True
```
